spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      database: products_db
  kafka:
    consumer:
      group-id: product-stock-update
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092

server:
  port=: 8081
