server:
  port: 8084

logging:
  level:
    root: INFO

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cart-services
      auto-offset-reset: earliest
  data:
    mongodb:
      database: shopping_cart_query_db
